# Generated by Django 3.2.7 on 2021-10-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('registered_dttm', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '장고스타그램 사용자',
                'verbose_name_plural': '장고스타그램 사용자',
                'db_table': 'Djangostar_dsuser',
            },
        ),
    ]
