# Generated by Django 3.2.7 on 2021-10-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsuser',
            options={},
        ),
        migrations.AlterField(
            model_name='dsuser',
            name='password',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='dsuser',
            name='username',
            field=models.CharField(max_length=6),
        ),
    ]
