# Generated by Django 3.2.7 on 2021-10-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tag',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Djangostar_tag',
        ),
    ]
